language: ruby
rvm:
  - 2.0.0

addons:
  code_climate:
    repo_token:

env:
  - RUBY_GC_MALLOC_LIMIT=90000000 RUBY_FREE_MIN=200000 SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql
  - redis-server

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER trello-release WITH PASSWORD 'trello-release';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS trello-release_test;" -U postgres
  - psql -c "CREATE DATABASE trello-release_test ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate test:prepare

script:
  - bundle exec rspec
  - bundle exec cucumber
  - bundle exec rubocop app spec features -R --format simple

notifications:
  email:
    recipients:
      - trello-release-dev@wolox.com.ar

cache:
  bundler: true
